### ISSUE TITLE
"Invalid memory access" from the touched action

### ISSUE THREAD

**Issue by palfrey** [cds-snc/github-actions#16]
I'm getting `Invalid memory access (signal 11) at address 0x0` from `cdssnc/touched-github-action` while running under [act](https://github.com/nektos/act) on OS X.  My pattern is `frontend/**`.

Any thoughts?

**Comment by maxneuvians** [comment]
Hi @palfrey, thank you for trying out the action! I am going to see if it has something to do with `act` or the action itself. We have it running in a couple of workflows without problems, but I would like to ensure that it is indeed something with the way `act` works. If it is then it is something we can feedback into `act` or fix on our end. Stay tuned!

**Comment by maxneuvians** [comment]
I narrowed it down to the following issue. The `touched` action requires there to be an `event.json` file that is parsed for any modified or new files:

https://github.com/cds-snc/github-actions/blob/master/touched/src/touched.cr#L24

`act` does not seem to provide this file, which is not the case for a normal GitHub action. The solution according to this issue (https://github.com/nektos/act/issues/44) is to use the `-e` flag. 

I have tested this with a simple main.workflow:

```
workflow "touched test" {
  on = "push"
  resolves = [
    "touched action"
  ]
}

action "touched action" {
  uses = "docker://cdssnc/touched-github-action:latest"
  args = "test/**"
}
```

If you run this with `act` you will get the error you encountered:
```
$ act
[touched action] docker run image=cdssnc/touched-github-action:latest entrypoint=[] cmd=["test/**"]
Invalid memory access (signal 11) at address 0x0
Error: exit with `FAILURE`: 139
```

If you specify a `event.json` payload (you can find one here: https://github.com/cds-snc/github-actions/blob/master/touched/spec/mock.js) - then it works:

```
$ act -e mock.js
[touched action] docker run image=cdssnc/touched-github-action:latest entrypoint=[] cmd=["test/**"]
Error: exit with `NEUTRAL`: 78
```

GitHub makes a claim about the certainty of that file always being there, but we will get that scenario fixed eventually.

Let me know if that answers your question!

**Comment by palfrey** [comment]
Thanks, that's really useful!
